baseURL: "https://www.flynnblair.com/"
title: Flynn Blair
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    menu:
      main:
        # - name: Archive
        #   url: archive/
        #   weight: 5
        - name: Books
          url: books/
          weight: 5
        - name: Blog
          url: posts/
          weight: 5
        # - name: Tags
        #   url: tags
        #   weight: 10
        # - name: Categories
        #   url: categories
        #   weight: 10
        # - name: Series
        #   url: series
        #   weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Flynn Blair

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  # ShowReadingTime: true
  disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  # comments: false
  images: ["papermod-cover.png"]

  homeInfoParams:
    Title: "Flynn Blair"
    Content: >
      Welcome to my writings and mind! I hope you enjoy your stay, because you can never leave.
      <br/><br/>
      **Progress on first book:** 
      <span style="color:green">Outlined</span> → 
      **<span style="color:green">Writing</span>** → 
      <span>Edited</span> → 
      <span>Published</span>
      <br/>
      **Words written:** 59,675 / ~80,000
      <br/>
      **Last written:** “Never,” said Koal. He whipped out his arms and covered the room in blackness.
  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/flynnblairbooks/"
    - name: youtube
      url: "https://www.youtube.com/channel/UCgfJf94e5bth0eKrYZeYHlQ"


  # editPost:
  #   URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
# taxonomies:
#   year: year
#   month: month
# permalinks:
#   post: "/posts/:year/:month/:slug/"
#   year: "/posts/:slug/"
#   month: "/posts/:slug/"
